# Homework 1-1: PLA

First, we use an artificial data set to study PLA. The data set is in https://www.csie.ntu.edu.tw/~htlin/course/ml15fall/hw1/hw1_15_train.dat

Each line of the data set contains one (x n ,y n ) with x n ∈ R 4 . The first 4 numbers of the line contains
the components of x n orderly, the last number is y n . Please initialize your algorithm with w = 0 and
take sign(0) as −1. As a friendly reminder, remember to add x 0 = 1 as always!

**1. Implement a version of PLA by visiting examples in the na¨ıve cycle using the order of examples in the data set. Run the algorithm on the data set. What is the number of updates before the algorithm halts? **

Load the dataset

In [1]:
from loadfile import *
from PerceptronLinearAlgorithm import *

In [2]:
X_data, Y_data = loadfile('./data/hw1_15_train.dat')

In [3]:
X_data

array([[ 0.97681 ,  0.10723 ,  0.64385 ,  0.29556 ],
       [ 0.67194 ,  0.2418  ,  0.83075 ,  0.42741 ],
       [ 0.20619 ,  0.23321 ,  0.81004 ,  0.98691 ],
       ..., 
       [ 0.93895 ,  0.93941 ,  0.72496 ,  0.95655 ],
       [ 0.046136,  0.94413 ,  0.038311,  0.26812 ],
       [ 0.072491,  0.2242  ,  0.62592 ,  0.67238 ]])

In [4]:
Y_data

array([ 1.,  1.,  1.,  1.,  1.,  1., -1.,  1., -1., -1.,  1.,  1.,  1.,
       -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
       -1.,  1.,  1., -1., -1.,  1.,  1., -1.,  1.,  1., -1., -1.,  1.,
       -1., -1.,  1., -1.,  1.,  1.,  1., -1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., -1., -1.,  1., -1.,  1., -1., -1.,  1.,
       -1.,  1., -1., -1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,  1.,
        1., -1.,  1.,  1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,  1.,  1.,
       -1.,  1.,  1.,  1.,  1., -1.,  1., -1.,  1.,  1., -1.,  1.,  1.,
        1.,  1., -1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1., -1., -1.,  1.,  1., -1.,  1., -1.,  1.,  1.,  1., -1.,  1.,
       -1., -1.,  1., -1., -1.,  1.,  1.,  1.,  1., -1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1., -1., -1., -1.,  1., -1.,  1., -1.,  1.,
       -1.,  1.,  1., -1., -1.,  1., -1.,  1.,  1.,  1.,  1.,  1

Data preprocess

In [5]:
# Add bias
X_data = np.hstack((np.ones((X_data.shape[0],1)), X_data))
# weights initialization
W = np.zeros(X_data.shape[1])

In [6]:
X_data

array([[ 1.      ,  0.97681 ,  0.10723 ,  0.64385 ,  0.29556 ],
       [ 1.      ,  0.67194 ,  0.2418  ,  0.83075 ,  0.42741 ],
       [ 1.      ,  0.20619 ,  0.23321 ,  0.81004 ,  0.98691 ],
       ..., 
       [ 1.      ,  0.93895 ,  0.93941 ,  0.72496 ,  0.95655 ],
       [ 1.      ,  0.046136,  0.94413 ,  0.038311,  0.26812 ],
       [ 1.      ,  0.072491,  0.2242  ,  0.62592 ,  0.67238 ]])

In [7]:
W

array([ 0.,  0.,  0.,  0.,  0.])

PLA iteration

In [8]:
PLA = pla()
halt = PLA.pla_1(X_data, Y_data)
print(halt)

37


**2. Implement a version of PLA by visiting examples in fixed, pre-determined random cycles
throughout the algorithm. Run the algorithm on the data set. Please repeat your experiment for
2000 times, each with a different random seed. What is the average number of updates before the
algorithm halts?**

In [9]:
halt, accuracy = PLA.pla_2(X_data, Y_data)
print(halt)

34.2895


** 3. Implement a version of PLA by visiting examples in fixed, pre-determined random cycles throughout the algorithm, while changing the update rule to be:**

$$W_{t+1}\rightarrow W_t+\eta y_{n(t)}x_{n(t)}$$

**with $\eta=0.5$. Note that your PLA in the previous problem corresponds to $\eta=1$. Please repeat your experiment for 2000 times, each with a different random seed. What is the average number of updates before the algorithm halts? **

In [10]:
halt, accuracy = PLA.pla_3(X_data, Y_data)
print(halt)

34.2895


# Homework 1-2: Pocket PLA

Next, we play with the pocket algorithm. Modify your PLA in Problem 16 to visit examples purely randomly, and then add the ‘pocket’ steps to the algorithm. We will use https://www.csie.ntu.edu.tw/~htlin/course/ml15fall/hw1/hw1_18_train.dat as the training data set D, and https://www.csie.ntu.edu.tw/~htlin/course/ml15fall/hw1/hw1_18_test.dat as the test set for “verifying” the g returned by your algorithm (see lecture 4 about verifying). The sets are of the same format as the previous one.

**1. Run the pocket algorithm with a total of 50 updates on D, and verify the performance of w pocket using the test set. Please repeat your experiment for 2000 times, each with a different random seed. What is the average error rate on the test set? **

Load the dataset

In [11]:
# train data
X_train, Y_train = loadfile('./data/hw1_18_train.dat')
# test data
X_test, Y_test = loadfile('./data/hw1_18_test.dat')

Data preprocess

In [12]:
# Add bias
X_train = np.hstack((np.ones((X_train.shape[0],1)), X_train))
X_test = np.hstack((np.ones((X_test.shape[0],1)), X_test))

In [13]:
X_train

array([[ 1.      ,  0.94544 ,  0.42842 ,  0.79833 ,  0.16244 ],
       [ 1.      ,  0.85365 ,  0.084168,  0.5682  ,  0.49221 ],
       [ 1.      ,  0.17095 ,  0.82127 ,  0.98444 ,  0.51486 ],
       ..., 
       [ 1.      ,  0.078827,  0.3823  ,  0.13965 ,  0.82677 ],
       [ 1.      ,  0.92288 ,  0.86313 ,  0.22939 ,  0.92214 ],
       [ 1.      ,  0.50315 ,  0.41884 ,  0.026094,  0.91623 ]])

In [14]:
X_test

array([[ 1.      ,  0.62926 ,  0.32783 ,  0.010417,  0.73102 ],
       [ 1.      ,  0.32368 ,  0.61439 ,  0.42097 ,  0.025626],
       [ 1.      ,  0.15968 ,  0.83346 ,  0.97515 ,  0.32762 ],
       ..., 
       [ 1.      ,  0.34445 ,  0.30929 ,  0.049222,  0.49242 ],
       [ 1.      ,  0.040789,  0.28334 ,  0.55817 ,  0.60612 ],
       [ 1.      ,  0.36302 ,  0.34961 ,  0.12651 ,  0.54315 ]])

Pocket PLA iteration

In [15]:
PocketPLA = pocket_pla()
error_mean = PocketPLA.pocket_pla_1(X_train, Y_train, X_test, Y_test)
print(error_mean)

0.287786


**2. Modify your algorithm to return $w_{50}$(the PLA vector after 50 updates) instead of w (the pocket vector) after 50 updates. Run the modified algorithm on D, and verify the performance using the test set. Please repeat your experiment for 2000 times, each with a different random seed. What is the average error rate on the test set? Compare your result to the previous problem and briefly discuss your findings.**

In [16]:
error_mean = PocketPLA.pocket_pla_2(X_train, Y_train, X_test, Y_test)
print(error_mean)

0.300748


**3. Modify your algorithm in Problem 18 to run for 100 updates instead of 50, and verify the performance of w pocket using the test set. Please repeat your experiment for 2000 times, each with a different random seed. What is the average error rate on the test set?**

In [17]:
error_mean = PocketPLA.pocket_pla_3(X_train, Y_train, X_test, Y_test)
print(error_mean)

0.287875
